name: "CI"

on:
  push:
    branches: [ "main","ci/cd409221" ]

  pull_request:
    branches: [ "main","ci/cd409221" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test square
        run: square.py .
      - name: Run test circle
        run: circle.py .
      - name: Run test triangle
        run: triangle.py .
      - name: Run test rectangle
        run: rectangle.py .

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: action/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test square
        run: square.py .
      - name: Run test circle
        run: circle.py .
      - name: Run test triangle
        run: triangle.py .
      - name: Run test rectangle
        run: rectangle.py .




